// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _SAMPLES_CALCULATOR_H_
#define _SAMPLES_CALCULATOR_H_

#include <staff/common/IService.h>
#include <string>
#include <vector>
namespace samples
{

  //! Calculator service
  class Calculator: public staff::IService
  {
  public:
    // *restMethod: GET
    // *restLocation: Word/context={context}
virtual std::vector<std::string> Word(std::string context) = 0;
    // *restMethod: GET
    // *restLocation: Add/a={a},b={b}
virtual int Add(int a, int b) = 0;
    // *restMethod: GET
    // *restLocation: Sub/a={a},b={b}
virtual int Sub(int a, int b) = 0;
    // add your opperations here. Example:
    // virtual void MyOperation() = 0;
  };

}

#endif // _SAMPLES_CALCULATOR_H_
