// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#ifndef _CalculatorImpl_h_
#define _CalculatorImpl_h_

#include "Calculator.h"
#include <vector>
namespace samples
{
	
	//! implementation of Calculator service
	class CalculatorImpl: public Calculator
		{
		public:
			CalculatorImpl();
			virtual ~CalculatorImpl();
			virtual void OnCreate();
			virtual void OnDestroy();
			virtual std::vector<std::string> Word(std::string context);
			virtual int Add(int a, int b);
			virtual int Sub(int a, int b);
		};
}


#endif // _CalculatorImpl_h_
